/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgwiRouteImport } from './routes/ogwi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EarlyWarningRouteImport } from './routes/early-warning'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsIndexRouteImport } from './routes/simulations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SimulationsIdRouteImport } from './routes/simulations/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'

const OgwiRoute = OgwiRouteImport.update({
  id: '/ogwi',
  path: '/ogwi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyWarningRoute = EarlyWarningRouteImport.update({
  id: '/early-warning',
  path: '/early-warning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIndexRoute = SimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIdRoute = SimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/early-warning': typeof EarlyWarningRoute
  '/login': typeof LoginRoute
  '/ogwi': typeof OgwiRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/simulations/$id': typeof SimulationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/early-warning': typeof EarlyWarningRoute
  '/login': typeof LoginRoute
  '/ogwi': typeof OgwiRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/simulations/$id': typeof SimulationsIdRoute
  '/admin': typeof AdminIndexRoute
  '/simulations': typeof SimulationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/early-warning': typeof EarlyWarningRoute
  '/login': typeof LoginRoute
  '/ogwi': typeof OgwiRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/simulations/$id': typeof SimulationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/early-warning'
    | '/login'
    | '/ogwi'
    | '/admin/agents'
    | '/admin/users'
    | '/simulations/$id'
    | '/admin/'
    | '/simulations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/early-warning'
    | '/login'
    | '/ogwi'
    | '/admin/agents'
    | '/admin/users'
    | '/simulations/$id'
    | '/admin'
    | '/simulations'
  id:
    | '__root__'
    | '/'
    | '/early-warning'
    | '/login'
    | '/ogwi'
    | '/admin/agents'
    | '/admin/users'
    | '/simulations/$id'
    | '/admin/'
    | '/simulations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarlyWarningRoute: typeof EarlyWarningRoute
  LoginRoute: typeof LoginRoute
  OgwiRoute: typeof OgwiRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SimulationsIdRoute: typeof SimulationsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ogwi': {
      id: '/ogwi'
      path: '/ogwi'
      fullPath: '/ogwi'
      preLoaderRoute: typeof OgwiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-warning': {
      id: '/early-warning'
      path: '/early-warning'
      fullPath: '/early-warning'
      preLoaderRoute: typeof EarlyWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof SimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$id': {
      id: '/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/simulations/$id'
      preLoaderRoute: typeof SimulationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarlyWarningRoute: EarlyWarningRoute,
  LoginRoute: LoginRoute,
  OgwiRoute: OgwiRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  SimulationsIdRoute: SimulationsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
