/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as SrmRouteImport } from './routes/srm'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OgwiRouteImport } from './routes/ogwi'
import { Route as MyActivitiesRouteImport } from './routes/my-activities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlobalPerspectivesRouteImport } from './routes/global-perspectives'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EarlyWarningRouteImport } from './routes/early-warning'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsIndexRouteImport } from './routes/simulations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SimulationsIdRouteImport } from './routes/simulations/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const SrmRoute = SrmRouteImport.update({
  id: '/srm',
  path: '/srm',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OgwiRoute = OgwiRouteImport.update({
  id: '/ogwi',
  path: '/ogwi',
  getParentRoute: () => rootRouteImport,
} as any)
const MyActivitiesRoute = MyActivitiesRouteImport.update({
  id: '/my-activities',
  path: '/my-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPerspectivesRoute = GlobalPerspectivesRouteImport.update({
  id: '/global-perspectives',
  path: '/global-perspectives',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyWarningRoute = EarlyWarningRouteImport.update({
  id: '/early-warning',
  path: '/early-warning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIndexRoute = SimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIdRoute = SimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/early-warning': typeof EarlyWarningRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/global': typeof GlobalRoute
  '/global-perspectives': typeof GlobalPerspectivesRoute
  '/login': typeof LoginRoute
  '/my-activities': typeof MyActivitiesRoute
  '/ogwi': typeof OgwiRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/srm': typeof SrmRoute
  '/travel': typeof TravelRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/simulations/$id': typeof SimulationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/early-warning': typeof EarlyWarningRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/global': typeof GlobalRoute
  '/global-perspectives': typeof GlobalPerspectivesRoute
  '/login': typeof LoginRoute
  '/my-activities': typeof MyActivitiesRoute
  '/ogwi': typeof OgwiRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/srm': typeof SrmRoute
  '/travel': typeof TravelRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/simulations/$id': typeof SimulationsIdRoute
  '/admin': typeof AdminIndexRoute
  '/simulations': typeof SimulationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/early-warning': typeof EarlyWarningRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/global': typeof GlobalRoute
  '/global-perspectives': typeof GlobalPerspectivesRoute
  '/login': typeof LoginRoute
  '/my-activities': typeof MyActivitiesRoute
  '/ogwi': typeof OgwiRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/srm': typeof SrmRoute
  '/travel': typeof TravelRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/simulations/$id': typeof SimulationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/early-warning'
    | '/forgot-password'
    | '/global'
    | '/global-perspectives'
    | '/login'
    | '/my-activities'
    | '/ogwi'
    | '/onboarding'
    | '/reset-password'
    | '/srm'
    | '/travel'
    | '/admin/agents'
    | '/admin/users'
    | '/simulations/$id'
    | '/admin/'
    | '/simulations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/early-warning'
    | '/forgot-password'
    | '/global'
    | '/global-perspectives'
    | '/login'
    | '/my-activities'
    | '/ogwi'
    | '/onboarding'
    | '/reset-password'
    | '/srm'
    | '/travel'
    | '/admin/agents'
    | '/admin/users'
    | '/simulations/$id'
    | '/admin'
    | '/simulations'
  id:
    | '__root__'
    | '/'
    | '/early-warning'
    | '/forgot-password'
    | '/global'
    | '/global-perspectives'
    | '/login'
    | '/my-activities'
    | '/ogwi'
    | '/onboarding'
    | '/reset-password'
    | '/srm'
    | '/travel'
    | '/admin/agents'
    | '/admin/users'
    | '/simulations/$id'
    | '/admin/'
    | '/simulations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarlyWarningRoute: typeof EarlyWarningRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GlobalRoute: typeof GlobalRoute
  GlobalPerspectivesRoute: typeof GlobalPerspectivesRoute
  LoginRoute: typeof LoginRoute
  MyActivitiesRoute: typeof MyActivitiesRoute
  OgwiRoute: typeof OgwiRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SrmRoute: typeof SrmRoute
  TravelRoute: typeof TravelRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SimulationsIdRoute: typeof SimulationsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srm': {
      id: '/srm'
      path: '/srm'
      fullPath: '/srm'
      preLoaderRoute: typeof SrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogwi': {
      id: '/ogwi'
      path: '/ogwi'
      fullPath: '/ogwi'
      preLoaderRoute: typeof OgwiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-activities': {
      id: '/my-activities'
      path: '/my-activities'
      fullPath: '/my-activities'
      preLoaderRoute: typeof MyActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-perspectives': {
      id: '/global-perspectives'
      path: '/global-perspectives'
      fullPath: '/global-perspectives'
      preLoaderRoute: typeof GlobalPerspectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-warning': {
      id: '/early-warning'
      path: '/early-warning'
      fullPath: '/early-warning'
      preLoaderRoute: typeof EarlyWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof SimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$id': {
      id: '/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/simulations/$id'
      preLoaderRoute: typeof SimulationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarlyWarningRoute: EarlyWarningRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GlobalRoute: GlobalRoute,
  GlobalPerspectivesRoute: GlobalPerspectivesRoute,
  LoginRoute: LoginRoute,
  MyActivitiesRoute: MyActivitiesRoute,
  OgwiRoute: OgwiRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SrmRoute: SrmRoute,
  TravelRoute: TravelRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  SimulationsIdRoute: SimulationsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
